services:
    senky.api.graphql.context:
        class: senky\api\graphql\context
        arguments:
            - '@dbal.conn'
            - '@senky.api.graphql.buffer.forum_buffer'
            - '@senky.api.graphql.buffer.post_buffer'
            - '@senky.api.graphql.buffer.topic_buffer'

    senky.api.graphql.buffer.forum_buffer:
        class: senky\api\graphql\buffer\forum_buffer
        arguments:
            - '@dbal.conn'
            - '%tables.forums%'

    senky.api.graphql.buffer.post_buffer:
        class: senky\api\graphql\buffer\post_buffer
        arguments:
            - '@dbal.conn'
            - '%tables.posts%'

    senky.api.graphql.buffer.topic_buffer:
        class: senky\api\graphql\buffer\topic_buffer
        arguments:
            - '@dbal.conn'
            - '%tables.topics%'
